### PR TITLE
Added contract search filters

### LINKED ISSUE #45: Añadir busqueda de Entidad
**Is your feature request related to a problem? Please describe.**

Quiero buscar entidades y poder ver detalles del mismo, como contratos y tendencias de ellos.

**Describe the solution you'd like**

Ingresar un `entity id` (el id usado por https://consultacontratos.ocpr.gov.pr/) para hacer una busqueda de entidad o contratista especifico.

**Describe alternatives you've considered**

1. Que el campo de buqueda cambie su contexto cuando se este viendo contratos o entidades.
2. Crear un tipo de DSL para poder hacer busquedas avanzadas.
  Eg. `entity_id: 3125` devolveria `Autoridad de Carreteras ....`
 Para esto se tiene que hacer un mapping de enttity_id a source_id.

**Additional context**

 La pagina del contralor esta ofreciendo data dumps en formato `csv`. El nosotros no poder filtrar o buscar por numero de entidad podria ser un problema para nosotros y nuestros usuarios.

### PR DESCRIPTION
**Pull request by froi**
*Note*: Before submitting this pull request, please review our [contributing guidelines](https://github.com/TheIndexingProject/contratospr-api/blob/master/CONTRIBUTING.md).

## Description

I've added some additional search filters to the contracts search.

- Entity `id`
- Entity `source_id`

This PR closes #45

### CODE REVIEW

**Comment by froi** [comment]
@jpadilla Estoy teniendo problemas con el filtro por `source_id`. Cuando eso este listo haré el full PR.

https://github.com/TheIndexingProject/contratospr-api/blob/5b118f31f0d6b17944dde2e79f4035639f307e1d/contratospr/contracts/search.py#L44

**Comment by jpadilla** [comment]
@froi we're actually not using this method anymore after implementing filtering/search in the API. Should be safe to remove.

https://github.com/TheIndexingProject/contratospr-api/blob/a9573becade8c5097b7875257b55939ad76a3aa1/contratospr/api/filters.py#L18

https://github.com/TheIndexingProject/contratospr-api/blob/a9573becade8c5097b7875257b55939ad76a3aa1/contratospr/api/filters.py#L49

**Comment by froi** [comment]
@jpadilla Yep, I noticed that a bit too late. I'm still working on this. I'm trying to get the API to filter by `source_id` for the `Entity` endpoints.

I'm getting the following error when using a `ModelMultipleChoiceFilter` on the source_id field

image

The filtering works well when using a `NumericFilter` and just one value.

**Comment by froi** [comment]
Creo que este PR ya no es relevante, oh mas bien esta muy separado del `master` branch. Closing for now.

**Pull request closed without merging**
